kind: List
apiVersion: v1
items:
  - kind: Service
    apiVersion: v1
    metadata:
      name: iam-id-mgmt-db
    spec:
      clusterIP: None
      selector:
        app: iam-id-mgmt-db
      ports:
      - name: pgsql
        port: 5432
  - kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: iam-id-mgmt-db
    spec:
      serviceName: iam-id-mgmt-db
      selector:
        matchLabels:
          app: iam-id-mgmt-db
      replicas: 1
      template:
        metadata:
          labels:
            app: iam-id-mgmt-db
        spec:            
          containers:
          - name: iam-id-mgmt-db
            image: localhost:32000/postgres:alpine
            env:
            - name: POSTGRES_PASSWORD
              value: Password1
            - name: POSTGRES_USER
              value: samplesam
            - name: POSTGRES_DB
              value: defaultdb
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            ports:
            - name: postgresql
              containerPort: 5432
            volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data/pgdata
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1Mi
          accessModes:
          - ReadWriteOnce





