kind: Job
apiVersion: batch/v1
metadata:
  name: iam-id-mgmt-job-initialize-db
spec:
  template:
    metadata:
      labels:
        app: iam-id-mgmt-job-initialize-db
    spec:
      restartPolicy: OnFailure
      containers:
      - name: initializer
        image: localhost:32000/iam-id-mgmt-api-service
        workingDir: /app/IdentityManagement/IdentityManagement.Data
        command: ["dotnet"]
        args: ["ef", "database", "update"]
        volumeMounts:
        - name: datadbconfig
          mountPath: /app/IdentityManagement/IdentityManagement.Data/config
          readOnly: true
      volumes:
      - name: datadbconfig
        configMap:
          name: iam-id-mgmt-dbconfigs
