kind: Job
apiVersion: batch/v1
metadata:
  name: iam-id-mgmt-job-integration-tests
spec:
  template:
    metadata:
      labels:
        app: iam-id-mgmt-job-integration-tests
    spec:
      restartPolicy: OnFailure
      containers:
      - name: integration-tests
        image: localhost:32000/iam-id-mgmt-api-service
        workingDir: /app/IdentityManagement/IdentityManagement.UnitTests
        command: ["dotnet"]
        args: ["test"]
        env: 
        - name: targetDomainForTests
          value: http://iam-id-mgmt-api-service-public:2080
        volumeMounts:
        - name: datadbconfig
          mountPath: /app/IdentityManagement/IdentityManagement.UnitTests/config
          readOnly: true
      volumes:
      - name: datadbconfig
        configMap:
          name: iam-id-mgmt-dbconfigs
