kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-volume-pgsql-identity
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: persistent-volume-pgsql-identity
    fsType: nfs4