kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: identitymanagement-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identitymanagement-api-service
  template:
    metadata:
      labels:
        app: identitymanagement-api-service
    spec:
      containers:
      - name: identitymanagement-api-service
        image: localhost:32000/identitymanagement-api-service
        workingDir: /app/IdentityManagement/IdentityManagement.Api
        command: ["dotnet"]
        args: ["run"]
        readinessProbe:
          httpGet:
            path: /ping
            port: 2083
          initialDelaySeconds: 10
          periodSeconds: 10            
        livenessProbe:
          httpGet:
            path: /ping
            port: 2083
          initialDelaySeconds: 120
          periodSeconds: 10            
        ports:
        - name: https
          protocol: TCP
          containerPort: 443
        - name: http
          protocol: TCP
          containerPort: 2083
        volumeMounts:
        - name: datadbconfig
          mountPath: /app/IdentityManagement/IdentityManagement.Api/config
          readOnly: true
      volumes:
      - name: datadbconfig
        configMap:
          name: identitymanagement-dbconfigs
